In [ ]:
# Install the following modules
!pip install pandas_datareader

In [ ]:
# Install the openpyxl package to handle excel files properly
!pip install openpyxl

In [ ]:
import warnings
warnings.simplefilter("ignore")

In [ ]:
# Clears all variable values previously set
from IPython import get_ipython
# get_ipython().magic('reset -sf')

In [ ]:
!pip install numpy

In [ ]:
!pip install pandas

In [2]:
# Provides ways to work with large multidimensional arrays
import numpy as np 
# Allows for further data manipulation and analysis
import pandas as pd

# In Anaconda -> Environments -> Not Installed -> pandas-datareader -> Apply
from pandas_datareader import data as web # Reads stock data 
import matplotlib.pyplot as plt # Plotting
import matplotlib.dates as mdates # Styling dates
%matplotlib inline

# Pandas

Pandas provides numerous tools to work with tabular data like you'd find in spreadsheets or databases. It is widely used for data preparation, cleaning, and analysis. It can work with a wide variety of data and provides many visualization options. It is built on top of NumPy.

## Read Data from HTML

In [ ]:
gov_data = pd.read_html("https://en.wikipedia.org/wiki/List_of_current_United_States_governors")
gov_data

In [ ]:
# We can define that we want the 2nd table on the page
gov_data = pd.read_html("https://en.wikipedia.org/wiki/List_of_current_United_States_governors")[1]
gov_data.head(5)

In [ ]:
# Delete a level of a multilevel column name
# gov_data.columns = gov_data.columns.droplevel()
gov_data.head(2)

In [ ]:
#List all the available columns
gov_data.columns

In [ ]:
# Delete all the columns containining only "NaN" and "List" Value
gov_data = gov_data.drop(['Image', 'Party[14]','Ref.'], axis=1)
gov_data.head(5)

## Rename the "Party.1" column

In [ ]:
# You could add additional with commas between {}
gov_data = gov_data.rename(columns={'Party[14].1': 'Party'})

gov_data.head(5)

In [ ]:
# You could add additional with commas between {}

gov_data = gov_data.rename(columns={'End of term[14]': 'End of term'})

gov_data = gov_data.rename(columns={'Governor[14]': 'Governor'})

gov_data = gov_data.rename(columns={'Inauguration[14]': 'Inauguration'})

gov_data = gov_data.rename(columns={'Prior public experience[15]': 'Prior public experience'})

gov_data.head(5)

In [ ]:
gov_data[:5]

In [ ]:
# Create a column for the age of Governors
gov_data['Gov_Age'] = gov_data['Born'].str.split('\(age').str[1]
# extract any opening and closing bracket and everything inside with nothing("")
gov_data[:5]

In [ ]:
print(gov_data.columns)

In [ ]:
# Remove parentheses and whats inside them
gov_data['Gov_Age'] = gov_data['Gov_Age'].str.replace(r")","") 
# replaces any opening and closing bracket and everything inside with nothing("")
gov_data[:5]

In [ ]:
# Remove parentheses and whats inside them
gov_data['Gov_Age'] = gov_data['Gov_Age'].str.replace(r")","") 
number_columns = ['Gov_Age']
for column in number_columns:
    gov_data[column] = gov_data[column].astype ('int16')
# replaces any opening and closing bracket and everything inside with nothing("")
gov_data[:5]

In [ ]:
# First, extract the necessary columns
gov_data.columns

In [ ]:
# Rearranging the columns to place the Gov_Age near the born Column
gov_data = gov_data[['State', 'Governor', 'Party', 'Born', 'Gov_Age', 'Prior public experience',
       'Inauguration', 'End of term']]
gov_data

## Remove Characters in Columns

In [ ]:
# Remove parentheses and whats inside them
gov_data['End of term'] = gov_data['End of term'].str.replace(r"\(.*\)","", regex=True) 
# replaces any opening bracket with nothing
gov_data

In [ ]:
# Extracting All the entire columns headers
print(list(gov_data.columns))

In [ ]:
# Removing parentheses and whats inside them for all the Columns
df_headers = ['State', 'Governor', 'Party', 'Born', 'Prior public experience', 'Inauguration']

for header in df_headers:
    gov_data[header] = gov_data[header].str.replace(r"\(.*\)","", regex=True) 
# replaces any opening and closing bracket and everything inside with nothing("")
gov_data[:5]

In [ ]:
gov_data[31:48:16]

In [ ]:
# Remove square parentheses and whats inside them
gov_data['End of term'] = gov_data['End of term'].str.replace(r"\[.*\]","", regex=True) 
# replaces any opening and closing bracket and everything inside with nothing("")
gov_data[31:48:16]

In [ ]:
# Removing square parentheses and whats inside them for all the Columns
df_headers = ['State', 'Governor', 'Party', 'Born', 'Prior public experience', 'Inauguration', 'End of term']

for header in df_headers:
    gov_data[header] = gov_data[header].str.replace(r"\[.*\]","", regex=True) 
# replaces any opening and closing bracket and everything inside with nothing("")

gov_data[31:48:16]

In [ ]:
# "^–*.\w$

In [ ]:
# Investigating the Party Column in line 22
gov_data[22:23]

In [ ]:
# Remove the dash(-) symbol parentheses and what follows in line 22 and replace with nothing
gov_data ['Party'] = gov_data ['Party'].astype (str)
gov_data['Party'] = gov_data['Party'].str.replace(r"–Farmer–Labor","") 
# replaces any opening and closing bracket and everything inside with nothing("")
gov_data[22:23]

In [ ]:
# Investigating the Governor Column in line 3 and 30
gov_data[3:31:27]

In [ ]:
# Replacing the middle name  of the two Governors with initials
gov_data['Governor'] = gov_data['Governor'].str.replace(r"Sarah Huckabee Sanders","Sarah H. Sanders") 
gov_data['Governor'] = gov_data['Governor'].str.replace(r"Michelle Lujan Grisham","Michelle L. Grisham")
gov_data[3:31:27]

In [ ]:
# Confirming the structure of our dataframe
gov_data.info()

In [ ]:
# Confirming the number of columns
print(f"The number of columns are: {len(gov_data.columns)}")
gov_data.columns

In [ ]:
# Changing all the columns with the object data type to string
number_columns = ['State', 'Governor', 'Party', 'Born', 'Prior public experience']
for column in number_columns:
    gov_data[column] = gov_data[column].astype ("string")
    
gov_data.info()

In [ ]:
# Changing the columns with the object data type to date
date_columns = ['Born','Inauguration']
for column in date_columns:
    gov_data[column] = pd.to_datetime(gov_data[column],format="mixed")
    
gov_data.info()

In [ ]:
number_columns = ['End of term']
for column in number_columns:
    gov_data[column] = gov_data[column].astype ('int16') # int16 ranges from -32,686 to 32,687
    
gov_data.info()

In [ ]:
gov_data[0:5]

In [ ]:
# Formatting  the datetime in the Born and Inauguration columns into Nigeria format
# Changing the columns with the object data type to date
date_columns = ['Born','Inauguration']
for column in date_columns:
    gov_data[column] = gov_data[column].dt.strftime('%d-%b-%Y') # e.g 10-Jan-2023

gov_data[0:5]

In [ ]:
# Delete all the columns containining only "NaN" and "List" Value
gov_data = gov_data.drop(['Prior public experience'], axis=1)
gov_data.head(5)

In [ ]:
# Confirming that the right data are in few columns

In [ ]:
# Checking the State Column 
print(list(gov_data['State'].unique()))

In [ ]:
# Checking the State Column 
print(list(gov_data['Party'].unique()))

In [ ]:
gov_data['Party'] = gov_data['Party'].str.replace(r" ","") 
print(list(gov_data['Party'].unique()))

In [ ]:
# Checking the State Column 
print(list(gov_data['End of term'].unique()))

In [ ]:
# Checking Final Summary before Exporting
gov_data.head(5)

In [ ]:
import datetime
now_date = datetime.datetime.now()
now_date

In [ ]:
string_now = str(now_date.year)+ "_"+str(now_date.month)+ "_"+str(now_date.day)+"_"+str(now_date.hour)+"_"+str(now_date.minute)
string_now

In [ ]:
date_time = now_date.strftime("%Y_%m_%d_%H_%M")
date_time

In [ ]:
#Exporting our gov_data dataframe as CSV File
try:
    gov_data.to_excel("US_Governors_List_"+date_time+".xlsx",index=False)
except:
    print("Error: Unable to convert dataframe to a excel file")
else:
    print("The Excel file successfully created.")

In [ ]:
pwd

## US Demographics

In [5]:
# You can also search for phrases in the table
d_data = pd.read_html("https://en.wikipedia.org/wiki/Demographics_of_the_United_States", 
                      match="Average population")
d_data

[                 Year Average population Live births [83]  Deaths [fn 1]  \
 0                1909           90490000          2718000            NaN
 1                1910           92407000          2777000            NaN
 2                1911           93863000          2809000            NaN
 3                1912           95335000          2840000            NaN
 4                1913           97225000          2869000            NaN
 ..                ...                ...              ...            ...
 111  2020[87][88][89]     331,577,720[a]          3613647      3383729.0
 112  2021[91][92][93]     332,099,760[a]          3664292      3464231.0
 113  2022[94][95][93]     334,017,321[a]          3667758      3279857.0
 114          2023[96]     336,806,231[a]          3596017      3090964.0
 115  2024p[b][96][97]          340110988    3,628,934[98]      3072551.0

      Natural change  Crude birth rate (per 1,000)  \
 0               NaN                          30.0
 1               NaN                          30.1
 2               NaN                          29.9
 3               NaN                          29.8
 4               NaN                          29.5
 ..              ...                           ...
 111        229918.0                          10.9
 112        200061.0                          11.0
 113        387901.0                          11.0
 114        505053.0                          10.7
 115        556383.0                          10.7

      Crude death rate (per 1,000)[84]  Natural change (per 1,000)  \
 0                                 NaN                         NaN
 1                                 NaN                         NaN
 2                                 NaN                         NaN
 3                                 NaN                         NaN
 4                                 NaN                         NaN
 ..                                ...                         ...
 111                              10.2                         0.7
 112                              10.4                         0.6
 113                               9.8                         1.2
 114                               9.2                         1.5
 115                               9.0                         1.6

      Crude migration change (per 1,000) Total fertility rate[fn 2][68][85][86]
 0                                   NaN                                   3.58
 1                                   NaN                                   3.59
 2                                   NaN                                   3.57
 3                                   NaN                                   3.56
 4                                   NaN                                   3.45
 ..                                  ...                                    ...
 111                                 3.0                                  1.641
 112                                 1.1                              1.664[93]
 113                                 5.1                              1.656[93]
 114                                 6.8                                  1.621
 115                                 8.2                                  1.599

 [116 rows x 10 columns]]

In [6]:
# You can also search for phrases in the table
d_data = pd.read_html("https://en.wikipedia.org/wiki/Demographics_of_the_United_States", 
                      match="Average population")[0]
d_data

,Year,Average population,Live births [83],Deaths [fn 1],Natural change,"Crude birth rate (per 1,000)","Crude death rate (per 1,000)[84]","Natural change (per 1,000)","Crude migration change (per 1,000)",Total fertility rate[fn 2][68][85][86]
0,1909,90490000,2718000,NaN,NaN,30.0,NaN,NaN,NaN,3.58
1,1910,92407000,2777000,NaN,NaN,30.1,NaN,NaN,NaN,3.59
2,1911,93863000,2809000,NaN,NaN,29.9,NaN,NaN,NaN,3.57
3,1912,95335000,2840000,NaN,NaN,29.8,NaN,NaN,NaN,3.56
4,1913,97225000,2869000,NaN,NaN,29.5,NaN,NaN,NaN,3.45
...,...,...,...,...,...,...,...,...,...,...
111,2020[87][88][89],"331,577,720[a]",3613647,3383729.0,229918.0,10.9,10.2,0.7,3.0,1.641
112,2021[91][92][93],"332,099,760[a]",3664292,3464231.0,200061.0,11.0,10.4,0.6,1.1,1.664[93]
113,2022[94][95][93],"334,017,321[a]",3667758,3279857.0,387901.0,11.0,9.8,1.2,5.1,1.656[93]
114,2023[96],"336,806,231[a]",3596017,3090964.0,505053.0,10.7,9.2,1.5,6.8,1.621
115,2024p[b][96][97],340110988,"3,628,934[98]",3072551.0,556383.0,10.7,9.0,1.6,8.2,1.599

In [7]:
d_data.columns

Index(['Year', 'Average population', 'Live births [83]', 'Deaths [fn 1]',
       'Natural change', 'Crude birth rate (per 1,000)',
       'Crude death rate (per 1,000)[84]', 'Natural change (per 1,000)',
       'Crude migration change (per 1,000)',
       'Total fertility rate[fn 2][68][85][86]'],
      dtype='object')

## Replace Spaces in Column Names

In [8]:
d_data.columns = [x.replace(' ', '_') for x in d_data.columns]
d_data

,Year,Average_population,Live_births_[83],Deaths_[fn_1],Natural_change,"Crude_birth_rate_(per_1,000)","Crude_death_rate_(per_1,000)[84]","Natural_change_(per_1,000)","Crude_migration_change_(per_1,000)",Total_fertility_rate[fn_2][68][85][86]
0,1909,90490000,2718000,NaN,NaN,30.0,NaN,NaN,NaN,3.58
1,1910,92407000,2777000,NaN,NaN,30.1,NaN,NaN,NaN,3.59
2,1911,93863000,2809000,NaN,NaN,29.9,NaN,NaN,NaN,3.57
3,1912,95335000,2840000,NaN,NaN,29.8,NaN,NaN,NaN,3.56
4,1913,97225000,2869000,NaN,NaN,29.5,NaN,NaN,NaN,3.45
...,...,...,...,...,...,...,...,...,...,...
111,2020[87][88][89],"331,577,720[a]",3613647,3383729.0,229918.0,10.9,10.2,0.7,3.0,1.641
112,2021[91][92][93],"332,099,760[a]",3664292,3464231.0,200061.0,11.0,10.4,0.6,1.1,1.664[93]
113,2022[94][95][93],"334,017,321[a]",3667758,3279857.0,387901.0,11.0,9.8,1.2,5.1,1.656[93]
114,2023[96],"336,806,231[a]",3596017,3090964.0,505053.0,10.7,9.2,1.5,6.8,1.621
115,2024p[b][96][97],340110988,"3,628,934[98]",3072551.0,556383.0,10.7,9.0,1.6,8.2,1.599

In [ ]:
for column in d_data.columns:
    print(column)
    #column.replace(' ', '_',inplace =True)

In [9]:
d_data.columns

Index(['Year', 'Average_population', 'Live_births_[83]', 'Deaths_[fn_1]',
       'Natural_change', 'Crude_birth_rate_(per_1,000)',
       'Crude_death_rate_(per_1,000)[84]', 'Natural_change_(per_1,000)',
       'Crude_migration_change_(per_1,000)',
       'Total_fertility_rate[fn_2][68][85][86]'],
      dtype='object')

## Remove Characters in Columns

In [10]:
# Remove parentheses and whats inside them
d_data.columns = d_data.columns.str.replace(r"\(.*\)","", regex=True) 
# replaces any opening and closing bracket and everything inside with nothing("")
d_data.head(5)

,Year,Average_population,Live_births_[83],Deaths_[fn_1],Natural_change,Crude_birth_rate_,Crude_death_rate_[84],Natural_change_,Crude_migration_change_,Total_fertility_rate[fn_2][68][85][86]
0,1909,90490000,2718000,NaN,NaN,30.0,NaN,NaN,NaN,3.58
1,1910,92407000,2777000,NaN,NaN,30.1,NaN,NaN,NaN,3.59
2,1911,93863000,2809000,NaN,NaN,29.9,NaN,NaN,NaN,3.57
3,1912,95335000,2840000,NaN,NaN,29.8,NaN,NaN,NaN,3.56
4,1913,97225000,2869000,NaN,NaN,29.5,NaN,NaN,NaN,3.45

In [11]:
# Remove the square brackets and whatever is inside them
d_data.columns = d_data.columns.str.replace(r"\[.*\]","", regex=True)
# replaces any opening and closing square bracket and everything inside with nothing("")
d_data.head(5)

,Year,Average_population,Live_births_,Deaths_,Natural_change,Crude_birth_rate_,Crude_death_rate_,Natural_change_,Crude_migration_change_,Total_fertility_rate
0,1909,90490000,2718000,NaN,NaN,30.0,NaN,NaN,NaN,3.58
1,1910,92407000,2777000,NaN,NaN,30.1,NaN,NaN,NaN,3.59
2,1911,93863000,2809000,NaN,NaN,29.9,NaN,NaN,NaN,3.57
3,1912,95335000,2840000,NaN,NaN,29.8,NaN,NaN,NaN,3.56
4,1913,97225000,2869000,NaN,NaN,29.5,NaN,NaN,NaN,3.45

## Rename Columns

In [12]:
# You could add additional with commas between {}
#d_data = d_data.rename(columns={'Unnamed:_0': 'Year'})

d_data

,Year,Average_population,Live_births_,Deaths_,Natural_change,Crude_birth_rate_,Crude_death_rate_,Natural_change_,Crude_migration_change_,Total_fertility_rate
0,1909,90490000,2718000,NaN,NaN,30.0,NaN,NaN,NaN,3.58
1,1910,92407000,2777000,NaN,NaN,30.1,NaN,NaN,NaN,3.59
2,1911,93863000,2809000,NaN,NaN,29.9,NaN,NaN,NaN,3.57
3,1912,95335000,2840000,NaN,NaN,29.8,NaN,NaN,NaN,3.56
4,1913,97225000,2869000,NaN,NaN,29.5,NaN,NaN,NaN,3.45
...,...,...,...,...,...,...,...,...,...,...
111,2020[87][88][89],"331,577,720[a]",3613647,3383729.0,229918.0,10.9,10.2,0.7,3.0,1.641
112,2021[91][92][93],"332,099,760[a]",3664292,3464231.0,200061.0,11.0,10.4,0.6,1.1,1.664[93]
113,2022[94][95][93],"334,017,321[a]",3667758,3279857.0,387901.0,11.0,9.8,1.2,5.1,1.656[93]
114,2023[96],"336,806,231[a]",3596017,3090964.0,505053.0,10.7,9.2,1.5,6.8,1.621
115,2024p[b][96][97],340110988,"3,628,934[98]",3072551.0,556383.0,10.7,9.0,1.6,8.2,1.599

In [13]:
d_data.columns

Index(['Year', 'Average_population', 'Live_births_', 'Deaths_',
       'Natural_change', 'Crude_birth_rate_', 'Crude_death_rate_',
       'Natural_change_', 'Crude_migration_change_', 'Total_fertility_rate'],
      dtype='object')

## Remove any trailing underscores(_) from column names

In [14]:
d_data.columns = d_data.columns.str.replace(r"\_$","", regex=True) # ^_ for begining of column names with an _
# replaces any trailing underscores in the column names and replace with nothing("")
d_data

,Year,Average_population,Live_births,Deaths,Natural_change,Crude_birth_rate,Crude_death_rate,Natural_change,Crude_migration_change,Total_fertility_rate
0,1909,90490000,2718000,NaN,NaN,30.0,NaN,NaN,NaN,3.58
1,1910,92407000,2777000,NaN,NaN,30.1,NaN,NaN,NaN,3.59
2,1911,93863000,2809000,NaN,NaN,29.9,NaN,NaN,NaN,3.57
3,1912,95335000,2840000,NaN,NaN,29.8,NaN,NaN,NaN,3.56
4,1913,97225000,2869000,NaN,NaN,29.5,NaN,NaN,NaN,3.45
...,...,...,...,...,...,...,...,...,...,...
111,2020[87][88][89],"331,577,720[a]",3613647,3383729.0,229918.0,10.9,10.2,0.7,3.0,1.641
112,2021[91][92][93],"332,099,760[a]",3664292,3464231.0,200061.0,11.0,10.4,0.6,1.1,1.664[93]
113,2022[94][95][93],"334,017,321[a]",3667758,3279857.0,387901.0,11.0,9.8,1.2,5.1,1.656[93]
114,2023[96],"336,806,231[a]",3596017,3090964.0,505053.0,10.7,9.2,1.5,6.8,1.621
115,2024p[b][96][97],340110988,"3,628,934[98]",3072551.0,556383.0,10.7,9.0,1.6,8.2,1.599

In [15]:
d_data.columns

Index(['Year', 'Average_population', 'Live_births', 'Deaths', 'Natural_change',
       'Crude_birth_rate', 'Crude_death_rate', 'Natural_change',
       'Crude_migration_change', 'Total_fertility_rate'],
      dtype='object')

In [16]:
tuple(d_data)

('Year',
 'Average_population',
 'Live_births',
 'Deaths',
 'Natural_change',
 'Crude_birth_rate',
 'Crude_death_rate',
 'Natural_change',
 'Crude_migration_change',
 'Total_fertility_rate')

In [17]:
# Checking the summary of the table
d_data.describe()

,Deaths,Natural_change,Crude_birth_rate,Crude_death_rate,Natural_change,Crude_migration_change
count,9.200000e+01,9.200000e+01,116.000000,92.000000,92.000000,92.000000
mean,2.039157e+06,1.628221e+06,18.608621,9.177174,8.098913,2.663370
std,5.109340e+05,5.464742e+05,5.074378,0.817676,4.057729,5.842056
min,1.342106e+06,2.000610e+05,10.700000,7.900000,0.600000,-22.600000
25%,1.555536e+06,1.302635e+06,14.550000,8.600000,5.700000,1.800000
50%,1.968474e+06,1.635717e+06,17.700000,9.050000,7.000000,3.150000
75%,2.406620e+06,1.891000e+06,22.500000,9.600000,10.175000,4.100000
max,3.464231e+06,2.666872e+06,30.100000,11.500000,16.500000,41.000000

In [18]:
# Extracting the data information for the dataframe
d_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116 entries, 0 to 115
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Year                    116 non-null    object
 1   Average_population      116 non-null    object
 2   Live_births             116 non-null    object
 3   Deaths                  92 non-null     float64
 4   Natural_change          92 non-null     float64
 5   Crude_birth_rate        116 non-null    float64
 6   Crude_death_rate        92 non-null     float64
 7   Natural_change          92 non-null     float64
 8   Crude_migration_change  92 non-null     float64
 9   Total_fertility_rate    116 non-null    object
dtypes: float64(6), object(4)
memory usage: 9.2+ KB

In [19]:
# Selecting column headers for integers
int_data_columns = list(d_data.select_dtypes(include='int').columns) # number, float, bool, object, datetime
print(int_data_columns)

[]

In [ ]:
for column in int_data_columns:
    d_data[column] = d_data[column].astype ('int32') # int32 ranges from -2,147,483,648 to 2,147,483,647

d_data.info()

In [20]:
# Selecting column headers for float
float_data_columns = list(d_data.select_dtypes(include='float').columns)
print(float_data_columns)

['Deaths', 'Natural_change', 'Crude_birth_rate', 'Crude_death_rate', 'Natural_change', 'Crude_migration_change']

In [ ]:
for column in float_data_columns:
    d_data[column] = d_data[column].astype ('float16') #

d_data.info()

In [21]:
# Selecting column headers for objects
object_data_columns = list(d_data.select_dtypes(include='object').columns)
print(object_data_columns)

['Year', 'Average_population', 'Live_births', 'Total_fertility_rate']

In [22]:
#Investigating the unique values for year column
unique_years = d_data.Year.unique()
print(unique_years)

['1909' '1910' '1911' '1912' '1913' '1914' '1915' '1916' '1917' '1918'
 '1919' '1920' '1921' '1922' '1923' '1924' '1925' '1926' '1927' '1928'
 '1929' '1930' '1931' '1932' '1933' '1934' '1935' '1936' '1937' '1938'
 '1939' '1940' '1941' '1942' '1943' '1944' '1945' '1946' '1947' '1948'
 '1949' '1950' '1951' '1952' '1953' '1954' '1955' '1956' '1957' '1958'
 '1959' '1960' '1961' '1962' '1963' '1964' '1965' '1966' '1967' '1968'
 '1969' '1970' '1971' '1972' '1973' '1974' '1975' '1976' '1977' '1978'
 '1979' '1980' '1981' '1982' '1983' '1984' '1985' '1986' '1987' '1988'
 '1989' '1990' '1991' '1992' '1993' '1994' '1995' '1996' '1997' '1998'
 '1999' '2000' '2001' '2002' '2003' '2004' '2005' '2006' '2007' '2008'
 '2009' '2010' '2011' '2012' '2013' '2014' '2015' '2016' '2017' '2018'
 '2019' '2020[87][88][89]' '2021[91][92][93]' '2022[94][95][93]'
 '2023[96]' '2024p[b][96][97]']

In [23]:
# Cleaning up the square brackets and changing to the appropriate datatype
# Removing square parentheses and whats inside them for all the Columns
df_headers = ['Year']
for header in df_headers:
    d_data[header] = d_data[header].str.replace(r"\[.*\]","", regex=True)  # remove the square paretheses
#d_data[header] = d_data[header].astype("int16") # convert it data between -32,000 to +32,000

unique_years = d_data.Year.unique()
print(unique_years)

['1909' '1910' '1911' '1912' '1913' '1914' '1915' '1916' '1917' '1918'
 '1919' '1920' '1921' '1922' '1923' '1924' '1925' '1926' '1927' '1928'
 '1929' '1930' '1931' '1932' '1933' '1934' '1935' '1936' '1937' '1938'
 '1939' '1940' '1941' '1942' '1943' '1944' '1945' '1946' '1947' '1948'
 '1949' '1950' '1951' '1952' '1953' '1954' '1955' '1956' '1957' '1958'
 '1959' '1960' '1961' '1962' '1963' '1964' '1965' '1966' '1967' '1968'
 '1969' '1970' '1971' '1972' '1973' '1974' '1975' '1976' '1977' '1978'
 '1979' '1980' '1981' '1982' '1983' '1984' '1985' '1986' '1987' '1988'
 '1989' '1990' '1991' '1992' '1993' '1994' '1995' '1996' '1997' '1998'
 '1999' '2000' '2001' '2002' '2003' '2004' '2005' '2006' '2007' '2008'
 '2009' '2010' '2011' '2012' '2013' '2014' '2015' '2016' '2017' '2018'
 '2019' '2020' '2021' '2022' '2023' '2024p']

In [24]:
# checking the last five records
d_data.tail(5)

,Year,Average_population,Live_births,Deaths,Natural_change,Crude_birth_rate,Crude_death_rate,Natural_change,Crude_migration_change,Total_fertility_rate
111,2020,"331,577,720[a]",3613647,3383729.0,229918.0,10.9,10.2,0.7,3.0,1.641
112,2021,"332,099,760[a]",3664292,3464231.0,200061.0,11.0,10.4,0.6,1.1,1.664[93]
113,2022,"334,017,321[a]",3667758,3279857.0,387901.0,11.0,9.8,1.2,5.1,1.656[93]
114,2023,"336,806,231[a]",3596017,3090964.0,505053.0,10.7,9.2,1.5,6.8,1.621
115,2024p,340110988,"3,628,934[98]",3072551.0,556383.0,10.7,9.0,1.6,8.2,1.599

In [26]:
# Remove the extra p in the 2023 year column
d_data['Year'] = d_data['Year'].str.replace(r"p","", regex=True) 
# replaces any opening and closing bracket and everything inside with nothing("")
d_data.tail(5)

,Year,Average_population,Live_births,Deaths,Natural_change,Crude_birth_rate,Crude_death_rate,Natural_change,Crude_migration_change,Total_fertility_rate
111,2020,"331,577,720[a]",3613647,3383729.0,229918.0,10.9,10.2,0.7,3.0,1.641
112,2021,"332,099,760[a]",3664292,3464231.0,200061.0,11.0,10.4,0.6,1.1,1.664[93]
113,2022,"334,017,321[a]",3667758,3279857.0,387901.0,11.0,9.8,1.2,5.1,1.656[93]
114,2023,"336,806,231[a]",3596017,3090964.0,505053.0,10.7,9.2,1.5,6.8,1.621
115,2024,340110988,"3,628,934[98]",3072551.0,556383.0,10.7,9.0,1.6,8.2,1.599

In [27]:
# Cleaning up the square brackets and changing to the appropriate datatype
# Removing square parentheses and whats inside them for all the Columns
df_headers = ['Year']
for header in df_headers:
    d_data[header] = d_data[header].str.replace(r"\[.*\]","", regex=True)  # remove the square paretheses
    d_data[header] = d_data[header].astype("int16") # convert it data between -32,000 to +32,000

unique_years = d_data.Year.unique()
print(unique_years)

[1909 1910 1911 1912 1913 1914 1915 1916 1917 1918 1919 1920 1921 1922
 1923 1924 1925 1926 1927 1928 1929 1930 1931 1932 1933 1934 1935 1936
 1937 1938 1939 1940 1941 1942 1943 1944 1945 1946 1947 1948 1949 1950
 1951 1952 1953 1954 1955 1956 1957 1958 1959 1960 1961 1962 1963 1964
 1965 1966 1967 1968 1969 1970 1971 1972 1973 1974 1975 1976 1977 1978
 1979 1980 1981 1982 1983 1984 1985 1986 1987 1988 1989 1990 1991 1992
 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005 2006
 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020
 2021 2022 2023 2024]

In [33]:
# Cleaning up the square brackets and changing to the appropriate datatype
# Removing square parenthesis and whats inside them for all the columns
df_headers = ['Year']
for header in df_headers:
    # Ensure the column is treated as string first
    d_data[header] = d_data[header].astype(str)
    
    d_data[header] = d_data[header].str.replace(r"\[.\]","",regex=True) # remove the square parenthesis
    d_data[header] = d_data[header].astype("int16") # convert it data between -32,000 to +32,000

unique_years = d_data.Year.unique()
print(unique_years)

[1909 1910 1911 1912 1913 1914 1915 1916 1917 1918 1919 1920 1921 1922
 1923 1924 1925 1926 1927 1928 1929 1930 1931 1932 1933 1934 1935 1936
 1937 1938 1939 1940 1941 1942 1943 1944 1945 1946 1947 1948 1949 1950
 1951 1952 1953 1954 1955 1956 1957 1958 1959 1960 1961 1962 1963 1964
 1965 1966 1967 1968 1969 1970 1971 1972 1973 1974 1975 1976 1977 1978
 1979 1980 1981 1982 1983 1984 1985 1986 1987 1988 1989 1990 1991 1992
 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005 2006
 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020
 2021 2022 2023 2024]

In [34]:
# Checking the summary to establish the data are valid
d_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116 entries, 0 to 115
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Year                    116 non-null    int16
 1   Average_population      116 non-null    object
 2   Live_births             116 non-null    object
 3   Deaths                  92 non-null     float64
 4   Natural_change          92 non-null     float64
 5   Crude_birth_rate        116 non-null    float64
 6   Crude_death_rate        92 non-null     float64
 7   Natural_change          92 non-null     float64
 8   Crude_migration_change  92 non-null     float64
 9   Total_fertility_rate    116 non-null    object
dtypes: float64(6), int16(1), object(3)
memory usage: 8.5+ KB

In [35]:
#Investigating the unique values for year column
unique_fertility_rate = d_data['Total_fertility_rate'].unique()
print(unique_fertility_rate)

['3.58' '3.59' '3.57' '3.56' '3.45' '3.52' '3.47' '3.333' '3.312' '3.068'
 '3.263' '3.326' '3.109' '3.101' '3.121' '3.012' '2.901' '2.824' '2.660'
 '2.532' '2.533' '2.402' '2.319' '2.172' '2.232' '2.189' '2.146' '2.173'
 '2.222' '2.301' '2.399' '2.628' '2.718' '2.568' '2.491' '2.943' '3.274'
 '3.110' '3.091' '3.269' '3.358' '3.424' '3.543' '3.580' '3.689' '3.767'
 '3.701' '3.670' '3.654' '3.629' '3.474' '3.208' '2.928' '2.736' '2.578'
 '2.477' '2.465' '2.480' '2.266' '2.010' '1.879' '1.835' '1.774' '1.738'
 '1.789' '1.760' '1.808' '1.839' '1.812' '1.827' '1.799' '1.806' '1.844'
 '1.837' '1.872' '1.934' '2.014' '2.081' '2.062' '2.046' '2.019' '2.001'
 '1.978' '1.976' '1.971' '1.999' '2.007' '2.056' '2.030' '2.020' '2.047'
 '2.051' '2.057' '2.108' '2.120' '2.072' '2.002' '1.931' '1.894' '1.880'
 '1.857' '1.862' '1.843' '1.820' '1.765' '1.729' '1.706' '1.641'
 '1.664[93]' '1.656[93]' '1.621' '1.599']

In [36]:
# Checking the summary again to establish the data are valid
d_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116 entries, 0 to 115
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Year                    116 non-null    int16
 1   Average_population      116 non-null    object
 2   Live_births             116 non-null    object
 3   Deaths                  92 non-null     float64
 4   Natural_change          92 non-null     float64
 5   Crude_birth_rate        116 non-null    float64
 6   Crude_death_rate        92 non-null     float64
 7   Natural_change          92 non-null     float64
 8   Crude_migration_change  92 non-null     float64
 9   Total_fertility_rate    116 non-null    object
dtypes: float64(6), int16(1), object(3)
memory usage: 8.5+ KB

In [38]:
unique_live_births = d_data.Live_births.unique()
print(unique_live_births)

['2718000' '2777000' '2809000' '2840000' '2869000' '2966000' '2965000'
 '2964000' '2944000' '2948000' '2740000' '2950000' '3055000' '2882000'
 '2910000' '2979000' '2909000' '2839000' '2802000' '2674000' '2582000'
 '2618000' '2506000' '2440000' '2307000' '2396000' '2377000' '2355000'
 '2413000' '2496000' '2466000' '2559000' '2703000' '2989000' '3104000'
 '2939000' '2858000' '3411000' '3817000' '3637000' '3649000' '3632000'
 '3823000' '3913000' '3965000' '4078000' '4104000' '4218000' '4308000'
 '4255000' '4244796' '4257850' '4268326' '4167362' '4098020' '4027490'
 '3760358' '3606274' '3520959' '3501564' '3600206' '3731386' '3555970'
 '3258411' '3136965' '3159958' '3144198' '3167788' '3326632' '3333279'
 '3494398' '3612258' '3629238' '3680537' '3638933' '3669141' '3760561'
 '3756547' '3809394' '3909510' '4040958' '4158212' '4110907' '4065014'
 '4000240' '3952767' '3899589' '3891494' '3880894' '3941553' '3959417'
 '4058814' '4025933' '4021726' '4089950' '4112052' '4138349' '4265555'
 '4316234' '4247694' '4130665' '3999386' '3953590' '3952841' '3932181'
 '3988076' '3978497' '3945875' '3855500' '3791712' '3747540' '3613647'
 '3664292' '3667758' '3596017' '3,628,934[98]']

In [54]:
d_data[['Live_births', 'Total_fertility_rate', 'Average_population']].tail()

C:\CHM Python Class\myenv_pydata\Lib\site-packages\pandas\io\formats\format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

     Live_births  Total_fertility_rate Average_population
111      3613647              1.640625     331,577,720[a]
112      3664292              1.664062     332,099,760[a]
113      3667758              1.656250     334,017,321[a]
114      3596017              1.621094     336,806,231[a]
115      3628934              1.598633          340110988

In [55]:
# Cleaning up the square brackets and changing to the appropriate datatype
# Removing square parentheses and whats inside them for all the Columns
df_headers = ['Live_births', 'Total_fertility_rate', 'Average_population']
for header in df_headers:
    d_data[header] = d_data[header].astype(str)
    
    d_data[header] = d_data[header].str.replace(r":\$*\d$","", regex=True)  # remove any ending colon, space and digits
    d_data[header] = d_data[header].str.replace(r"\[.*\]","", regex=True)  # remove the square paretheses
    d_data[header] = d_data[header].str.replace(r",", "",regex=True) # remove the comma symbol

unique_Live_births = d_data.Live_births.unique()
unique_Total_fertility_rate = d_data.Total_fertility_rate.unique()
unique_Average_population = d_data.Average_population.unique()
print("unique_Live_births:", unique_Live_births)
print("unique_Total_fertility_rate:", unique_Total_fertility_rate)
print("unique_Average_population:", unique_Average_population)

unique_Live_births: ['2718000' '2777000' '2809000' '2840000' '2869000' '2966000' '2965000'
 '2964000' '2944000' '2948000' '2740000' '2950000' '3055000' '2882000'
 '2910000' '2979000' '2909000' '2839000' '2802000' '2674000' '2582000'
 '2618000' '2506000' '2440000' '2307000' '2396000' '2377000' '2355000'
 '2413000' '2496000' '2466000' '2559000' '2703000' '2989000' '3104000'
 '2939000' '2858000' '3411000' '3817000' '3637000' '3649000' '3632000'
 '3823000' '3913000' '3965000' '4078000' '4104000' '4218000' '4308000'
 '4255000' '4244796' '4257850' '4268326' '4167362' '4098020' '4027490'
 '3760358' '3606274' '3520959' '3501564' '3600206' '3731386' '3555970'
 '3258411' '3136965' '3159958' '3144198' '3167788' '3326632' '3333279'
 '3494398' '3612258' '3629238' '3680537' '3638933' '3669141' '3760561'
 '3756547' '3809394' '3909510' '4040958' '4158212' '4110907' '4065014'
 '4000240' '3952767' '3899589' '3891494' '3880894' '3941553' '3959417'
 '4058814' '4025933' '4021726' '4089950' '4112052' '4138349' '4265555'
 '4316234' '4247694' '4130665' '3999386' '3953590' '3952841' '3932181'
 '3988076' '3978497' '3945875' '3855500' '3791712' '3747540' '3613647'
 '3664292' '3667758' '3596017' '3628934']
unique_Total_fertility_rate: ['3.58' '3.59' '3.57' '3.56' '3.45' '3.52' '3.47' '3.332' '3.312' '3.068'
 '3.264' '3.326' '3.11' '3.102' '3.121' '3.012' '2.9' '2.824' '2.66'
 '2.531' '2.533' '2.402' '2.318' '2.172' '2.232' '2.19' '2.146' '2.174'
 '2.223' '2.3' '2.398' '2.629' '2.719' '2.568' '2.49' '2.943' '3.273'
 '3.092' '3.27' '3.357' '3.424' '3.543' '3.69' '3.768' '3.701' '3.67'
 '3.654' '3.629' '3.475' '3.207' '2.928' '2.736' '2.578' '2.477' '2.465'
 '2.48' '2.266' '2.01' '1.879' '1.835' '1.774' '1.738' '1.789' '1.76'
 '1.808' '1.839' '1.812' '1.827' '1.799' '1.806' '1.844' '1.837' '1.872'
 '1.934' '2.014' '2.08' '2.062' '2.047' '2.02' '2.002' '1.978' '1.976'
 '1.971' '1.999' '2.008' '2.057' '2.03' '2.05' '2.107' '2.12' '2.072'
 '1.931' '1.894' '1.88' '1.857' '1.862' '1.843' '1.82' '1.765' '1.729'
 '1.706' '1.641' '1.664' '1.656' '1.621' '1.599']
unique_Average_population: ['90490000' '92407000' '93863000' '95335000' '97225000' '99111000'
 '100546000' '101961000' '103268000' '103208000' '104514000' '106461000'
 '108538000' '110049000' '111947000' '114109000' '115828000' '117397000'
 '119085000' '120509000' '121767000' '123077000' '124040000' '124840000'
 '125579000' '126374000' '127250000' '128053000' '128825000' '129825000'
 '130880000' '131930000' '133058000' '133752000' '133971000' '132622000'
 '132137000' '139893000' '143375000' '146045000' '148558000' '151240000'
 '153384000' '155761000' '158313000' '161191000' '164302000' '167261000'
 '170295000' '173239000' '176511000' '179977000' '182953000' '185771000'
 '188483000' '191141000' '193526000' '195576000' '197457000' '199399000'
 '201385000' '203984000' '206827000' '209284000' '211357000' '213342000'
 '215465000' '217563000' '219760000' '222095000' '224567000' '227225000'
 '229466000' '231664000' '233792000' '235825000' '237924000' '240133000'
 '242289000' '244499000' '246819000' '249623000' '252981000' '256514000'
 '259919000' '263126000' '266278000' '269394000' '272647000' '275854000'
 '279040000' '282162411' '284968955' '287625193' '290107933' '292805298'
 '295516599' '298379912' '301231207' '304093966' '306771529' '309327143'
 '311849745' '314361094' '316755680' '319297805' '321882469' '324426311'
 '326686918' '328571142' '330284261' '331577720' '332099760' '334017321'
 '336806231' '340110988']

In [56]:
# converting Live births column to int and total fertility rate to float
d_data['Live_births'] = d_data['Live_births'].astype("int32") # convert it to data between -32,000 to +32,000
d_data['Total_fertility_rate'] = d_data['Total_fertility_rate'].astype("float16") # convert it to data between -32,000 to +32,000
d_data['Average_population'] = d_data['Average_population'].astype("int64")
d_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116 entries, 0 to 115
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Year                    116 non-null    int16
 1   Average_population      116 non-null    int64
 2   Live_births             116 non-null    int32
 3   Deaths                  92 non-null     float64
 4   Natural_change          92 non-null     float64
 5   Crude_birth_rate        116 non-null    float64
 6   Crude_death_rate        92 non-null     float64
 7   Natural_change          92 non-null     float64
 8   Crude_migration_change  92 non-null     float64
 9   Total_fertility_rate    116 non-null    float16
dtypes: float16(1), float64(6), int16(1), int32(1), int64(1)
memory usage: 7.4 KB

In [57]:
d_data.head(2)

C:\CHM Python Class\myenv_pydata\Lib\site-packages\pandas\io\formats\format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,Year,Average_population,Live_births,Deaths,Natural_change,Crude_birth_rate,Crude_death_rate,Natural_change,Crude_migration_change,Total_fertility_rate
0,1909,90490000,2718000,NaN,NaN,30.0,NaN,NaN,NaN,3.580078
1,1910,92407000,2777000,NaN,NaN,30.1,NaN,NaN,NaN,3.589844

In [58]:
d_data['Average_population'].unique()

array([ 90490000,  92407000,  93863000,  95335000,  97225000,  99111000,
       100546000, 101961000, 103268000, 103208000, 104514000, 106461000,
       108538000, 110049000, 111947000, 114109000, 115828000, 117397000,
       119085000, 120509000, 121767000, 123077000, 124040000, 124840000,
       125579000, 126374000, 127250000, 128053000, 128825000, 129825000,
       130880000, 131930000, 133058000, 133752000, 133971000, 132622000,
       132137000, 139893000, 143375000, 146045000, 148558000, 151240000,
       153384000, 155761000, 158313000, 161191000, 164302000, 167261000,
       170295000, 173239000, 176511000, 179977000, 182953000, 185771000,
       188483000, 191141000, 193526000, 195576000, 197457000, 199399000,
       201385000, 203984000, 206827000, 209284000, 211357000, 213342000,
       215465000, 217563000, 219760000, 222095000, 224567000, 227225000,
       229466000, 231664000, 233792000, 235825000, 237924000, 240133000,
       242289000, 244499000, 246819000, 249623000, 252981000, 256514000,
       259919000, 263126000, 266278000, 269394000, 272647000, 275854000,
       279040000, 282162411, 284968955, 287625193, 290107933, 292805298,
       295516599, 298379912, 301231207, 304093966, 306771529, 309327143,
       311849745, 314361094, 316755680, 319297805, 321882469, 324426311,
       326686918, 328571142, 330284261, 331577720, 332099760, 334017321,
       336806231, 340110988])

In [59]:
# Evaluating the summary of the dataframe
d_data.describe()

,Year,Average_population,Live_births,Deaths,Natural_change,Crude_birth_rate,Crude_death_rate,Natural_change,Crude_migration_change,Total_fertility_rate
count,116.000000,1.160000e+02,1.160000e+02,9.200000e+01,9.200000e+01,116.000000,92.000000,92.000000,92.000000,116.000000
mean,1966.500000,2.017228e+08,3.490605e+06,2.039157e+06,1.628221e+06,18.608621,9.177174,8.098913,2.663370,2.488281
std,33.630343,7.690735e+07,5.807118e+05,5.109340e+05,5.464742e+05,5.074378,0.817676,4.057729,5.842056,0.671387
min,1909.000000,9.049000e+07,2.307000e+06,1.342106e+06,2.000610e+05,10.700000,7.900000,0.600000,-22.600000,1.598633
25%,1937.750000,1.295750e+08,2.949500e+06,1.555536e+06,1.302635e+06,14.550000,8.600000,5.700000,1.800000,1.921387
50%,1966.500000,1.965165e+08,3.637966e+06,1.968474e+06,1.635717e+06,17.700000,9.050000,7.000000,3.150000,2.206055
75%,1995.250000,2.670570e+08,3.968374e+06,2.406620e+06,1.891000e+06,22.500000,9.600000,10.175000,4.100000,3.109375
max,2024.000000,3.401110e+08,4.316234e+06,3.464231e+06,2.666872e+06,30.100000,11.500000,16.500000,41.000000,3.767578

In [60]:
# Version 1 for single colums with no space in the column name
d_data.Live_births

0      2718000
1      2777000
2      2809000
3      2840000
4      2869000
        ...
111    3613647
112    3664292
113    3667758
114    3596017
115    3628934
Name: Live_births, Length: 116, dtype: int32

In [61]:
# Version 2 for single colums with space or no space in the column name
d_data['Deaths']

0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
         ...
111    3383729.0
112    3464231.0
113    3279857.0
114    3090964.0
115    3072551.0
Name: Deaths, Length: 116, dtype: float64

## Make a Column an Index

In [62]:
d_data.set_index('Year', inplace=True)
d_data

C:\CHM Python Class\myenv_pydata\Lib\site-packages\pandas\io\formats\format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,Average_population,Live_births,Deaths,Natural_change,Crude_birth_rate,Crude_death_rate,Natural_change,Crude_migration_change,Total_fertility_rate
Year,,,,,,,,,
1909,90490000,2718000,NaN,NaN,30.0,NaN,NaN,NaN,3.580078
1910,92407000,2777000,NaN,NaN,30.1,NaN,NaN,NaN,3.589844
1911,93863000,2809000,NaN,NaN,29.9,NaN,NaN,NaN,3.570312
1912,95335000,2840000,NaN,NaN,29.8,NaN,NaN,NaN,3.560547
1913,97225000,2869000,NaN,NaN,29.5,NaN,NaN,NaN,3.449219
...,...,...,...,...,...,...,...,...,...
2020,331577720,3613647,3383729.0,229918.0,10.9,10.2,0.7,3.0,1.640625
2021,332099760,3664292,3464231.0,200061.0,11.0,10.4,0.6,1.1,1.664062
2022,334017321,3667758,3279857.0,387901.0,11.0,9.8,1.2,5.1,1.656250
2023,336806231,3596017,3090964.0,505053.0,10.7,9.2,1.5,6.8,1.621094
2024,340110988,3628934,3072551.0,556383.0,10.7,9.0,1.6,8.2,1.598633

## Grab Data from Multiple Columns

In [63]:
d_data[["Live_births", "Deaths"]] # Multiple columns must be in double square bracket

      Live_births     Deaths
Year
1909      2718000        NaN
1910      2777000        NaN
1911      2809000        NaN
1912      2840000        NaN
1913      2869000        NaN
...           ...        ...
2020      3613647  3383729.0
2021      3664292  3464231.0
2022      3667758  3279857.0
2023      3596017  3090964.0
2024      3628934  3072551.0

[116 rows x 2 columns]

## Grab a Row

In [64]:
# Version 1
d_data.loc[2020]

Average_population        3.315777e+08
Live_births               3.613647e+06
Deaths                    3.383729e+06
Natural_change            2.299180e+05
Crude_birth_rate          1.090000e+01
Crude_death_rate          1.020000e+01
Natural_change            7.000000e-01
Crude_migration_change    3.000000e+00
Total_fertility_rate      1.640625e+00
Name: 2020, dtype: float64

In [66]:
d_data.iloc[85] # row 86 is 2021 (the last), row 85 is 2020

Average_population        2.631260e+08
Live_births               3.952767e+06
Deaths                    2.278994e+06
Natural_change            1.673773e+06
Crude_birth_rate          1.500000e+01
Crude_death_rate          8.700000e+00
Natural_change            6.400000e+00
Crude_migration_change    5.800000e+00
Total_fertility_rate      2.001953e+00
Name: 1994, dtype: float64

In [67]:
d_data.iloc[84:85] # Extracting the row horizontally

C:\CHM Python Class\myenv_pydata\Lib\site-packages\pandas\io\formats\format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,Average_population,Live_births,Deaths,Natural_change,Crude_birth_rate,Crude_death_rate,Natural_change,Crude_migration_change,Total_fertility_rate
Year,,,,,,,,,
1993,259919000,4000240,2268553.0,1731687.0,15.4,8.7,6.7,6.4,2.019531

In [69]:
d_data[84:86] # Extracting the row horizontally

C:\CHM Python Class\myenv_pydata\Lib\site-packages\pandas\io\formats\format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,Average_population,Live_births,Deaths,Natural_change,Crude_birth_rate,Crude_death_rate,Natural_change,Crude_migration_change,Total_fertility_rate
Year,,,,,,,,,
1993,259919000,4000240,2268553.0,1731687.0,15.4,8.7,6.7,6.4,2.019531
1994,263126000,3952767,2278994.0,1673773.0,15.0,8.7,6.4,5.8,2.001953

In [70]:
d_data.tail(5)

C:\CHM Python Class\myenv_pydata\Lib\site-packages\pandas\io\formats\format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,Average_population,Live_births,Deaths,Natural_change,Crude_birth_rate,Crude_death_rate,Natural_change,Crude_migration_change,Total_fertility_rate
Year,,,,,,,,,
2020,331577720,3613647,3383729.0,229918.0,10.9,10.2,0.7,3.0,1.640625
2021,332099760,3664292,3464231.0,200061.0,11.0,10.4,0.6,1.1,1.664062
2022,334017321,3667758,3279857.0,387901.0,11.0,9.8,1.2,5.1,1.656250
2023,336806231,3596017,3090964.0,505053.0,10.7,9.2,1.5,6.8,1.621094
2024,340110988,3628934,3072551.0,556383.0,10.7,9.0,1.6,8.2,1.598633

In [71]:
d_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 116 entries, 1909 to 2024
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Average_population      116 non-null    int64
 1   Live_births             116 non-null    int32
 2   Deaths                  92 non-null     float64
 3   Natural_change          92 non-null     float64
 4   Crude_birth_rate        116 non-null    float64
 5   Crude_death_rate        92 non-null     float64
 6   Natural_change          92 non-null     float64
 7   Crude_migration_change  92 non-null     float64
 8   Total_fertility_rate    116 non-null    float16
dtypes: float16(1), float64(6), int32(1), int64(1)
memory usage: 9.8 KB

In [72]:
d_data.columns

Index(['Average_population', 'Live_births', 'Deaths', 'Natural_change',
       'Crude_birth_rate', 'Crude_death_rate', 'Natural_change',
       'Crude_migration_change', 'Total_fertility_rate'],
      dtype='object')

In [73]:
d_data.head()

C:\CHM Python Class\myenv_pydata\Lib\site-packages\pandas\io\formats\format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,Average_population,Live_births,Deaths,Natural_change,Crude_birth_rate,Crude_death_rate,Natural_change,Crude_migration_change,Total_fertility_rate
Year,,,,,,,,,
1909,90490000,2718000,NaN,NaN,30.0,NaN,NaN,NaN,3.580078
1910,92407000,2777000,NaN,NaN,30.1,NaN,NaN,NaN,3.589844
1911,93863000,2809000,NaN,NaN,29.9,NaN,NaN,NaN,3.570312
1912,95335000,2840000,NaN,NaN,29.8,NaN,NaN,NaN,3.560547
1913,97225000,2869000,NaN,NaN,29.5,NaN,NaN,NaN,3.449219

In [74]:
# Keep only columns if they haven't used the same name prior.
# The code removes second columns with duplicated headings
d_data = d_data.loc[:,~d_data.columns.duplicated()] # ~ tilde
d_data.head(5)

C:\CHM Python Class\myenv_pydata\Lib\site-packages\pandas\io\formats\format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,Average_population,Live_births,Deaths,Natural_change,Crude_birth_rate,Crude_death_rate,Crude_migration_change,Total_fertility_rate
Year,,,,,,,,
1909,90490000,2718000,NaN,NaN,30.0,NaN,NaN,3.580078
1910,92407000,2777000,NaN,NaN,30.1,NaN,NaN,3.589844
1911,93863000,2809000,NaN,NaN,29.9,NaN,NaN,3.570312
1912,95335000,2840000,NaN,NaN,29.8,NaN,NaN,3.560547
1913,97225000,2869000,NaN,NaN,29.5,NaN,NaN,3.449219

In [75]:
# Specific columns can selected based on the column index from index 0 to the last index
d_data.iloc[0:,[0,2,7]]

C:\CHM Python Class\myenv_pydata\Lib\site-packages\pandas\io\formats\format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

      Average_population     Deaths  Total_fertility_rate
Year
1909            90490000        NaN              3.580078
1910            92407000        NaN              3.589844
1911            93863000        NaN              3.570312
1912            95335000        NaN              3.560547
1913            97225000        NaN              3.449219
...                  ...        ...                   ...
2020           331577720  3383729.0              1.640625
2021           332099760  3464231.0              1.664062
2022           334017321  3279857.0              1.656250
2023           336806231  3090964.0              1.621094
2024           340110988  3072551.0              1.598633

[116 rows x 3 columns]

In [76]:
d_data.head(5)

C:\CHM Python Class\myenv_pydata\Lib\site-packages\pandas\io\formats\format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,Average_population,Live_births,Deaths,Natural_change,Crude_birth_rate,Crude_death_rate,Crude_migration_change,Total_fertility_rate
Year,,,,,,,,
1909,90490000,2718000,NaN,NaN,30.0,NaN,NaN,3.580078
1910,92407000,2777000,NaN,NaN,30.1,NaN,NaN,3.589844
1911,93863000,2809000,NaN,NaN,29.9,NaN,NaN,3.570312
1912,95335000,2840000,NaN,NaN,29.8,NaN,NaN,3.560547
1913,97225000,2869000,NaN,NaN,29.5,NaN,NaN,3.449219

In [77]:
d_data.fillna(0, inplace = True)
d_data.head()

C:\Users\HP\AppData\Local\Temp\ipykernel_15920\693750636.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d_data.fillna(0, inplace = True)
C:\CHM Python Class\myenv_pydata\Lib\site-packages\pandas\io\formats\format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,Average_population,Live_births,Deaths,Natural_change,Crude_birth_rate,Crude_death_rate,Crude_migration_change,Total_fertility_rate
Year,,,,,,,,
1909,90490000,2718000,0.0,0.0,30.0,0.0,0.0,3.580078
1910,92407000,2777000,0.0,0.0,30.1,0.0,0.0,3.589844
1911,93863000,2809000,0.0,0.0,29.9,0.0,0.0,3.570312
1912,95335000,2840000,0.0,0.0,29.8,0.0,0.0,3.560547
1913,97225000,2869000,0.0,0.0,29.5,0.0,0.0,3.449219

In [78]:
d_data.to_excel("For inspection.xlsx")
print("Dataframe converted to Excel file successfully..")

Dataframe converted to Excel file successfully..

In [79]:
# Create a column showing population growth for each year
d_data['Pop_Growth'] = d_data["Live_births"] - d_data["Deaths"]
d_data

C:\CHM Python Class\myenv_pydata\Lib\site-packages\pandas\io\formats\format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,Average_population,Live_births,Deaths,Natural_change,Crude_birth_rate,Crude_death_rate,Crude_migration_change,Total_fertility_rate,Pop_Growth
Year,,,,,,,,,
1909,90490000,2718000,0.0,0.0,30.0,0.0,0.0,3.580078,2718000.0
1910,92407000,2777000,0.0,0.0,30.1,0.0,0.0,3.589844,2777000.0
1911,93863000,2809000,0.0,0.0,29.9,0.0,0.0,3.570312,2809000.0
1912,95335000,2840000,0.0,0.0,29.8,0.0,0.0,3.560547,2840000.0
1913,97225000,2869000,0.0,0.0,29.5,0.0,0.0,3.449219,2869000.0
...,...,...,...,...,...,...,...,...,...
2020,331577720,3613647,3383729.0,229918.0,10.9,10.2,3.0,1.640625,229918.0
2021,332099760,3664292,3464231.0,200061.0,11.0,10.4,1.1,1.664062,200061.0
2022,334017321,3667758,3279857.0,387901.0,11.0,9.8,5.1,1.656250,387901.0
2023,336806231,3596017,3090964.0,505053.0,10.7,9.2,6.8,1.621094,505053.0
2024,340110988,3628934,3072551.0,556383.0,10.7,9.0,8.2,1.598633,556383.0

## Adding another Dummy Column

In [80]:
# Create a column showing population growth for each year
d_data['Dummy_column'] = d_data["Crude_death_rate"] - d_data["Deaths"]
d_data[:5]

C:\CHM Python Class\myenv_pydata\Lib\site-packages\pandas\io\formats\format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,Average_population,Live_births,Deaths,Natural_change,Crude_birth_rate,Crude_death_rate,Crude_migration_change,Total_fertility_rate,Pop_Growth,Dummy_column
Year,,,,,,,,,,
1909,90490000,2718000,0.0,0.0,30.0,0.0,0.0,3.580078,2718000.0,0.0
1910,92407000,2777000,0.0,0.0,30.1,0.0,0.0,3.589844,2777000.0,0.0
1911,93863000,2809000,0.0,0.0,29.9,0.0,0.0,3.570312,2809000.0,0.0
1912,95335000,2840000,0.0,0.0,29.8,0.0,0.0,3.560547,2840000.0,0.0
1913,97225000,2869000,0.0,0.0,29.5,0.0,0.0,3.449219,2869000.0,0.0

## Delete Column

In [81]:
d_data.drop('Dummy_column', axis=1, inplace=True) # axis = 1 is for column, axis = 0 is for row
d_data

C:\CHM Python Class\myenv_pydata\Lib\site-packages\pandas\io\formats\format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,Average_population,Live_births,Deaths,Natural_change,Crude_birth_rate,Crude_death_rate,Crude_migration_change,Total_fertility_rate,Pop_Growth
Year,,,,,,,,,
1909,90490000,2718000,0.0,0.0,30.0,0.0,0.0,3.580078,2718000.0
1910,92407000,2777000,0.0,0.0,30.1,0.0,0.0,3.589844,2777000.0
1911,93863000,2809000,0.0,0.0,29.9,0.0,0.0,3.570312,2809000.0
1912,95335000,2840000,0.0,0.0,29.8,0.0,0.0,3.560547,2840000.0
1913,97225000,2869000,0.0,0.0,29.5,0.0,0.0,3.449219,2869000.0
...,...,...,...,...,...,...,...,...,...
2020,331577720,3613647,3383729.0,229918.0,10.9,10.2,3.0,1.640625,229918.0
2021,332099760,3664292,3464231.0,200061.0,11.0,10.4,1.1,1.664062,200061.0
2022,334017321,3667758,3279857.0,387901.0,11.0,9.8,5.1,1.656250,387901.0
2023,336806231,3596017,3090964.0,505053.0,10.7,9.2,6.8,1.621094,505053.0
2024,340110988,3628934,3072551.0,556383.0,10.7,9.0,8.2,1.598633,556383.0

## Delete a Row

In [82]:
d_data.drop(1909, axis=0, inplace=True) # x=0 is for row, x=1 is for column
d_data[:10]

C:\CHM Python Class\myenv_pydata\Lib\site-packages\pandas\io\formats\format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,Average_population,Live_births,Deaths,Natural_change,Crude_birth_rate,Crude_death_rate,Crude_migration_change,Total_fertility_rate,Pop_Growth
Year,,,,,,,,,
1910,92407000,2777000,0.0,0.0,30.1,0.0,0.0,3.589844,2777000.0
1911,93863000,2809000,0.0,0.0,29.9,0.0,0.0,3.570312,2809000.0
1912,95335000,2840000,0.0,0.0,29.8,0.0,0.0,3.560547,2840000.0
1913,97225000,2869000,0.0,0.0,29.5,0.0,0.0,3.449219,2869000.0
1914,99111000,2966000,0.0,0.0,29.9,0.0,0.0,3.570312,2966000.0
1915,100546000,2965000,0.0,0.0,25.1,0.0,0.0,3.519531,2965000.0
1916,101961000,2964000,0.0,0.0,25.0,0.0,0.0,3.470703,2964000.0
1917,103268000,2944000,0.0,0.0,24.7,0.0,0.0,3.332031,2944000.0
1918,103208000,2948000,0.0,0.0,24.6,0.0,0.0,3.312500,2948000.0
1919,104514000,2740000,0.0,0.0,22.3,0.0,0.0,3.068359,2740000.0

## List of Datatypes and value ranges

In [ ]:
# int8 / uint8 : consumes 1 byte of memory, range between -128/127 or 0/255

# bool : consumes 1 byte, true or false

# float16 / int16 / uint16: consumes 2 bytes of memory, range between -32,768 and 32,767 or 0/65,535

# float32 / int32 / uint32 : consumes 4 bytes of memory, range between -2,147,483,648 and 2,147,483,647

# float64 / int64 / uint64: consumes 8 bytes of memory

In [83]:
# Confirming the number of columns
print(f"The number of columns are: {len(d_data.columns)}")
d_data.columns

The number of columns are: 9

Index(['Average_population', 'Live_births', 'Deaths', 'Natural_change',
       'Crude_birth_rate', 'Crude_death_rate', 'Crude_migration_change',
       'Total_fertility_rate', 'Pop_Growth'],
      dtype='object')

In [84]:
# Confirming that all data are the right format
    
d_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 115 entries, 1910 to 2024
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Average_population      115 non-null    int64
 1   Live_births             115 non-null    int32
 2   Deaths                  115 non-null    float64
 3   Natural_change          115 non-null    float64
 4   Crude_birth_rate        115 non-null    float64
 5   Crude_death_rate        115 non-null    float64
 6   Crude_migration_change  115 non-null    float64
 7   Total_fertility_rate    115 non-null    float16
 8   Pop_Growth              115 non-null    float64
dtypes: float16(1), float64(6), int32(1), int64(1)
memory usage: 7.2 KB

In [85]:
# Exporting our gov_data dataframe as MS Excel File
try:
    d_data.to_excel("US_Population_data.xlsx")
except:
    print("Error: Unable to convert dataframe to as an MS excel file")
else:
    print("The Excel file successfully created.")

The Excel file successfully created.

## Manipulating Data

In [3]:
c_data = pd.read_html("https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)")[2]
c_data

    Country/Territory IMF[1][12]            World Bank[13]             \
    Country/Territory   Forecast       Year       Estimate       Year
0               World  113795678       2025      111326370       2024
1       United States   30507217       2025       29184890       2024
2               China   19231705  [n 1]2025       18743803  [n 3]2024
3             Germany    4744804       2025        4659929       2024
4               India    4187017       2025        3912686       2024
..                ...        ...        ...            ...        ...
217          Kiribati        312       2025            308       2024
218  Marshall Islands        297       2025            280       2024
219             Nauru        169       2025            160       2024
220        Montserrat          —          —              —          —
221            Tuvalu         65       2025             62       2023

    United Nations[14]
              Estimate       Year
0            100834796       2022
1             27720700       2023
2             17794782  [n 1]2023
3              4525704       2023
4              3575778       2023
..                 ...        ...
217                289       2023
218                270       2023
219                176       2023
220                 80       2023
221                 68       2023

[222 rows x 7 columns]

In [4]:
for col in c_data.columns:
    print(col)

('Country/Territory', 'Country/Territory')
('IMF[1][12]', 'Forecast')
('IMF[1][12]', 'Year')
('World Bank[13]', 'Estimate')
('World Bank[13]', 'Year')
('United Nations[14]', 'Estimate')
('United Nations[14]', 'Year')

In [5]:
# Delete a level of a multilevel column name
c_data.columns = c_data.columns.droplevel()
c_data

,Country/Territory,Forecast,Year,Estimate,Year,Estimate,Year
0,World,113795678,2025,111326370,2024,100834796,2022
1,United States,30507217,2025,29184890,2024,27720700,2023
2,China,19231705,[n 1]2025,18743803,[n 3]2024,17794782,[n 1]2023
3,Germany,4744804,2025,4659929,2024,4525704,2023
4,India,4187017,2025,3912686,2024,3575778,2023
...,...,...,...,...,...,...,...
217,Kiribati,312,2025,308,2024,289,2023
218,Marshall Islands,297,2025,280,2024,270,2023
219,Nauru,169,2025,160,2024,176,2023
220,Montserrat,—,—,—,—,80,2023
221,Tuvalu,65,2025,62,2023,68,2023

In [6]:
# Keep only columns if they haven't used the same name prior
# This codes removes "Estimate" column in column 7 and "Year" columns in column 6 and 8
c_data = c_data.loc[:,~c_data.columns.duplicated()]
c_data

    Country/Territory   Forecast       Year   Estimate
0               World  113795678       2025  111326370
1       United States   30507217       2025   29184890
2               China   19231705  [n 1]2025   18743803
3             Germany    4744804       2025    4659929
4               India    4187017       2025    3912686
..                ...        ...        ...        ...
217          Kiribati        312       2025        308
218  Marshall Islands        297       2025        280
219             Nauru        169       2025        160
220        Montserrat          —          —          —
221            Tuvalu         65       2025         62

[222 rows x 4 columns]

In [7]:
# Counting how many rows with NaN values by taking only rows that don't contain NaNs
c_data.isna().sum()

Country/Territory    0
Forecast             0
Year                 0
Estimate             0
dtype: int64

In [8]:
c_data[:5]

  Country/Territory   Forecast       Year   Estimate
0             World  113795678       2025  111326370
1     United States   30507217       2025   29184890
2             China   19231705  [n 1]2025   18743803
3           Germany    4744804       2025    4659929
4             India    4187017       2025    3912686

In [9]:
# Checking that all the columns have valid data
c_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 222 entries, 0 to 221
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Country/Territory  222 non-null    object
 1   Forecast           222 non-null    object
 2   Year               222 non-null    object
 3   Estimate           222 non-null    object
dtypes: object(4)
memory usage: 7.1+ KB

In [10]:
#Investigating the unique values for year column
unique_years = c_data.Year.unique()
print(unique_years)

['2025' '[n 1]2025' '[n 4]2025' '[n 5]2025' '—' '[n 6]2025' '[n 8]2025'
 '[n 9]2025' '[n 10]2025' '[n 11]2025']

In [11]:
# You can also investigating the unique values for year column using set data structure
unique_years_v2 = set(c_data.Year)
print(unique_years_v2)

{'[n 9]2025', '[n 8]2025', '[n 5]2025', '—', '[n 6]2025', '[n 1]2025', '[n 10]2025', '[n 11]2025', '[n 4]2025', '2025'}

In [12]:
# Remove []s and what is in them in Year column
# Removes brackets and what is inside for whole column
c_data.Year = c_data.Year.str.replace(r"\[.*\]","", regex=True)
unique_years_v2 = set(c_data.Year)
print(unique_years_v2)

{'2025', '—'}

C:\Users\HP\AppData\Local\Temp\ipykernel_1932\2145597198.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  c_data.Year = c_data.Year.str.replace(r"\[.*\]","", regex=True)

In [13]:
#Deleting rows in GDP column containing the special character (—)
c_data = c_data[~c_data.Year.str.contains("—", regex=False)]
unique_years_v2 = set(c_data.Year)
print(unique_years_v2)

{'2025'}

In [16]:
c_data.columns

Index(['Country/Territory', 'Forecast', 'Year', 'Estimate'], dtype='object')

In [17]:
# Rename country column
c_data.rename(columns={"Country/Territory": "Country", "Estimate": "GDP"}, 
              inplace=True)
c_data

C:\Users\HP\AppData\Local\Temp\ipykernel_1932\3543949302.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  c_data.rename(columns={"Country/Territory": "Country", "Estimate": "GDP"},

              Country   Forecast  Year        GDP
0               World  113795678  2025  111326370
1       United States   30507217  2025   29184890
2               China   19231705  2025   18743803
3             Germany    4744804  2025    4659929
4               India    4187017  2025    3912686
..                ...        ...   ...        ...
216             Palau        333  2025        282
217          Kiribati        312  2025        308
218  Marshall Islands        297  2025        280
219             Nauru        169  2025        160
221            Tuvalu         65  2025         62

[190 rows x 4 columns]

In [18]:
# You can also investigating the unique values for Country column using set data structure
unique_country_v2 = set(c_data.Country)
print(unique_country_v2)

{'Poland', 'Guinea-Bissau', 'Comoros', 'Eswatini', 'DR Congo', 'Cameroon', 'Kyrgyzstan', 'Maldives', 'Bulgaria', 'Seychelles', 'Austria', 'Hong Kong', 'Slovenia', 'Turkey', 'Uganda', 'Guatemala', 'Cyprus', 'El Salvador', 'Laos', 'Oman', 'Grenada', 'Zambia', 'Kazakhstan', 'Madagascar', 'Philippines', 'Italy', 'Netherlands', 'Puerto Rico', 'Panama', 'Mozambique', 'Brazil', 'Somalia', 'Turkmenistan', 'Mauritania', 'Namibia', 'Burundi', 'Ireland', 'Finland', 'Qatar', 'San Marino', 'Micronesia', 'Ivory Coast', 'Botswana', 'Iran', 'Colombia', 'Ethiopia', 'South Sudan', 'United States', 'Macau', 'Kenya', 'Ghana', 'Nigeria', 'Moldova', 'Spain', 'Tanzania', 'Myanmar', 'Dominican Republic', 'Marshall Islands', 'Denmark', 'Croatia', 'Guinea', 'Solomon Islands', 'Cambodia', 'Ukraine', 'Tuvalu', 'Vanuatu', 'Niger', 'Russia', 'Vietnam', 'Mongolia', 'United Kingdom', 'Bahrain', 'Nicaragua', 'Indonesia', 'Togo', 'Portugal', 'Cape Verde', 'Nepal', 'India', 'Tajikistan', 'Brunei', 'Libya', 'South Korea', 'Timor-Leste', 'Honduras', 'China', 'Burkina Faso', 'Benin', 'Azerbaijan', 'Costa Rica', 'Equatorial Guinea', 'Czech Republic', 'Lithuania', 'Jordan', 'Malta', 'Saint Lucia', 'Belarus', 'Mali', 'Nauru', 'Estonia', 'Fiji', 'Armenia', 'Sierra Leone', 'Algeria', 'Malawi', 'Samoa', 'Taiwan', 'Saint Kitts and Nevis', 'Georgia', 'Canada', 'Liberia', 'Gabon', 'Guyana', 'Peru', 'Papua New Guinea', 'Senegal', 'Japan', 'Ecuador', 'Luxembourg', 'Venezuela', 'Chile', 'Andorra', 'Hungary', 'Suriname', 'Paraguay', 'Zimbabwe', 'Greece', 'Lesotho', 'World', 'Switzerland', 'Antigua and Barbuda', 'Trinidad and Tobago', 'Chad', 'Sweden', 'Serbia', 'Bangladesh', 'Mauritius', 'Slovakia', 'Rwanda', 'South Africa', 'Belgium', 'Jamaica', 'France', 'Yemen', 'Tunisia', 'Djibouti', 'São Tomé and Príncipe', 'Aruba', 'Iceland', 'Belize', 'Congo', 'Kiribati', 'New Zealand', 'Uruguay', 'Bolivia', 'Germany', 'Sudan', 'Norway', 'Tonga', 'Palau', 'Kosovo', 'Central African Republic', 'Dominica', 'Angola', 'Australia', 'North Macedonia', 'Romania', 'Bosnia and Herzegovina', 'Egypt', 'Gambia', 'Thailand', 'United Arab Emirates', 'Malaysia', 'Kuwait', 'Latvia', 'Mexico', 'Iraq', 'Saint Vincent and the Grenadines', 'Albania', 'Bhutan', 'Morocco', 'Israel', 'Montenegro', 'Singapore', 'Uzbekistan', 'Saudi Arabia', 'Barbados', 'Argentina', 'Haiti', 'Bahamas'}

In [19]:
# Remove * in Country column
c_data.Country = c_data.Country.str.replace("*","",)
c_data

C:\Users\HP\AppData\Local\Temp\ipykernel_1932\3662679616.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  c_data.Country = c_data.Country.str.replace("*","",)

              Country   Forecast  Year        GDP
0               World  113795678  2025  111326370
1       United States   30507217  2025   29184890
2               China   19231705  2025   18743803
3             Germany    4744804  2025    4659929
4               India    4187017  2025    3912686
..                ...        ...   ...        ...
216             Palau        333  2025        282
217          Kiribati        312  2025        308
218  Marshall Islands        297  2025        280
219             Nauru        169  2025        160
221            Tuvalu         65  2025         62

[190 rows x 4 columns]

In [ ]:
# Install the openpyxl package to handle excel files properly
#!pip install openpyxl

In [20]:
# You can also investigating the unique values for Country column using set data structure
unique_gdp_v2 = set(c_data.GDP)
print(unique_gdp_v2)

{'4040', '49910', '1761', '111326370', '418542', '12109', '1161', '50183', '26326', '540380', '42914', '914696', '44188', '53652', '47737', '26588', '26429', '106943', '124499', '5841', '308683', '1832', '521642', '33776', '407107', '4659929', '124676', '160227', '25224', '19930', '664564', '23250', '92526', '19694', '32267', '17478', '14953', '282', '537079', '2272', '1068', '1323255', '4714', '11149', '3516', '16503', '24836', '936564', '1396300', '289222', '483727', '2752', '3162079', '280', '421972', '279641', '27178', '2167', '141776', '80962', '32538', '610118', '2225', '23586', '18200', '14252', '42765', '263620', '125842', '2768', '450119', '1157', '3649', '633267', '3019', '2372775', '330267', '20626', '49668', '1852723', '2241253', '37094', '89084', '14205', '62', '2549', '509', '1227544', '389050', '2179412', '1067', '124282', '112212', '29184890', '44458', '43521', '217983', '33463', '345037', '16685', '11009', '160', '86538', '24322', '18743803', '4086', '113200', '74316', '4892', '260236', '1391', '19538', '53352', '1237530', '1546', '4026211', '46636', '74080', '4750', '163698', '75962', '689', '3912686', '547387', '222905', '78780', '114965', '15833', '13372', '21483', '1722746', '187760', '—', '95350', '15463', '84869', '93197', '461618', '72485', '436906', '577389', '1752193', '2173836', '6975', '86260', '308', '1712793', '46353', '2162', '20867', '82825', '10767', '9926', '8070', '7165', '1881', '51327', '288406', '471', '190741', '257145', '764', '25787', '382768', '17421', '400261', '80397', '2508', '7548', '3643834', '15720', '64240', '476388', '35365', '154431', '22417', '70749', '25334', '12766', '28343', '526411', '429457', '53410', '299836', '36333', '19401', '2120'}

In [21]:
#Deleting rows in GDP column containing the special character (—)
c_data = c_data[~c_data.GDP.str.contains('—', regex=False)]
c_data

              Country   Forecast  Year        GDP
0               World  113795678  2025  111326370
1       United States   30507217  2025   29184890
2               China   19231705  2025   18743803
3             Germany    4744804  2025    4659929
4               India    4187017  2025    3912686
..                ...        ...   ...        ...
216             Palau        333  2025        282
217          Kiribati        312  2025        308
218  Marshall Islands        297  2025        280
219             Nauru        169  2025        160
221            Tuvalu         65  2025         62

[186 rows x 4 columns]

In [23]:
# You can also investigating the unique values for Country column using set data structure
unique_gdp_v2 = set(c_data.GDP)
print(unique_gdp_v2)

{'4040', '49910', '1761', '111326370', '418542', '12109', '1161', '50183', '26326', '540380', '42914', '914696', '44188', '53652', '47737', '26588', '26429', '106943', '124499', '5841', '308683', '1832', '521642', '33776', '407107', '4659929', '124676', '160227', '25224', '19930', '664564', '23250', '92526', '19694', '32267', '17478', '14953', '282', '537079', '2272', '1068', '1323255', '4714', '11149', '3516', '16503', '24836', '936564', '1396300', '289222', '483727', '2752', '3162079', '280', '421972', '279641', '27178', '2167', '141776', '80962', '32538', '610118', '2225', '23586', '18200', '14252', '42765', '263620', '125842', '2768', '450119', '1157', '3649', '633267', '3019', '2372775', '330267', '20626', '49668', '1852723', '2241253', '37094', '89084', '14205', '62', '2549', '509', '1227544', '389050', '2179412', '1067', '124282', '112212', '29184890', '44458', '43521', '217983', '33463', '345037', '16685', '11009', '160', '86538', '24322', '18743803', '4086', '113200', '74316', '4892', '260236', '1391', '19538', '53352', '1237530', '1546', '4026211', '46636', '74080', '4750', '163698', '75962', '689', '3912686', '547387', '222905', '78780', '114965', '15833', '13372', '21483', '1722746', '187760', '95350', '15463', '84869', '93197', '461618', '72485', '436906', '577389', '1752193', '2173836', '6975', '86260', '308', '1712793', '46353', '2162', '20867', '82825', '10767', '9926', '8070', '7165', '1881', '51327', '288406', '471', '190741', '257145', '764', '25787', '382768', '17421', '400261', '80397', '2508', '7548', '3643834', '15720', '64240', '476388', '35365', '154431', '22417', '70749', '25334', '12766', '28343', '526411', '429457', '53410', '299836', '36333', '19401', '2120'}

In [25]:
#Deleting rows in UN column containing the special character (—)
c_data = c_data[~c_data['Country'].str.contains("-", regex=False)]
c_data

              Country   Forecast  Year        GDP
0               World  113795678  2025  111326370
1       United States   30507217  2025   29184890
2               China   19231705  2025   18743803
3             Germany    4744804  2025    4659929
4               India    4187017  2025    3912686
..                ...        ...   ...        ...
216             Palau        333  2025        282
217          Kiribati        312  2025        308
218  Marshall Islands        297  2025        280
219             Nauru        169  2025        160
221            Tuvalu         65  2025         62

[184 rows x 4 columns]

In [26]:
# You can also investigating the unique values for Country column using set data structure
unique_country_v2 = set(c_data.Country)
print(unique_country_v2)

{'Poland', 'Comoros', 'Eswatini', 'DR Congo', 'Cameroon', 'Kyrgyzstan', 'Maldives', 'Bulgaria', 'Seychelles', 'Austria', 'Hong Kong', 'Slovenia', 'Turkey', 'Uganda', 'Guatemala', 'Cyprus', 'El Salvador', 'Laos', 'Oman', 'Grenada', 'Zambia', 'Kazakhstan', 'Madagascar', 'Philippines', 'Italy', 'Netherlands', 'Puerto Rico', 'Panama', 'Mozambique', 'Brazil', 'Somalia', 'Turkmenistan', 'Mauritania', 'Namibia', 'Burundi', 'Ireland', 'Finland', 'Qatar', 'San Marino', 'Micronesia', 'Ivory Coast', 'Botswana', 'Iran', 'Colombia', 'Ethiopia', 'United States', 'Macau', 'Kenya', 'Ghana', 'Nigeria', 'Moldova', 'Spain', 'Tanzania', 'Myanmar', 'Dominican Republic', 'Marshall Islands', 'Denmark', 'Croatia', 'Guinea', 'Solomon Islands', 'Cambodia', 'Ukraine', 'Tuvalu', 'Vanuatu', 'Niger', 'Russia', 'Vietnam', 'Mongolia', 'United Kingdom', 'Bahrain', 'Nicaragua', 'Indonesia', 'Togo', 'Portugal', 'Cape Verde', 'Nepal', 'India', 'Tajikistan', 'Brunei', 'Libya', 'South Korea', 'Honduras', 'China', 'Burkina Faso', 'Benin', 'Azerbaijan', 'Costa Rica', 'Equatorial Guinea', 'Czech Republic', 'Lithuania', 'Jordan', 'Malta', 'Saint Lucia', 'Belarus', 'Mali', 'Nauru', 'Estonia', 'Fiji', 'Armenia', 'Sierra Leone', 'Algeria', 'Malawi', 'Samoa', 'Saint Kitts and Nevis', 'Georgia', 'Canada', 'Liberia', 'Gabon', 'Guyana', 'Peru', 'Papua New Guinea', 'Senegal', 'Japan', 'Ecuador', 'Luxembourg', 'Chile', 'Andorra', 'Hungary', 'Suriname', 'Paraguay', 'Zimbabwe', 'Greece', 'Lesotho', 'World', 'Switzerland', 'Antigua and Barbuda', 'Trinidad and Tobago', 'Chad', 'Sweden', 'Serbia', 'Bangladesh', 'Mauritius', 'Slovakia', 'Rwanda', 'South Africa', 'Belgium', 'Jamaica', 'France', 'Tunisia', 'Djibouti', 'São Tomé and Príncipe', 'Aruba', 'Iceland', 'Belize', 'Congo', 'Kiribati', 'New Zealand', 'Uruguay', 'Bolivia', 'Germany', 'Sudan', 'Norway', 'Tonga', 'Palau', 'Kosovo', 'Central African Republic', 'Dominica', 'Angola', 'Australia', 'North Macedonia', 'Romania', 'Bosnia and Herzegovina', 'Egypt', 'Gambia', 'Thailand', 'United Arab Emirates', 'Malaysia', 'Kuwait', 'Latvia', 'Mexico', 'Iraq', 'Saint Vincent and the Grenadines', 'Albania', 'Bhutan', 'Morocco', 'Israel', 'Montenegro', 'Singapore', 'Uzbekistan', 'Saudi Arabia', 'Barbados', 'Argentina', 'Haiti', 'Bahamas'}

In [27]:
c_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 184 entries, 0 to 221
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Country   184 non-null    object
 1   Forecast  184 non-null    object
 2   Year      184 non-null    object
 3   GDP       184 non-null    object
dtypes: object(4)
memory usage: 7.2+ KB

In [28]:
# C0nfiguring the nummber of columns 
print(f'The number of columns are:{len(c_data.columns)}')
c_data.columns

The number of columns are:4

Index(['Country', 'Forecast', 'Year', 'GDP'], dtype='object')

In [29]:
# Changing all the columns with the object data type to string
number_columns = ['Country']
for column in number_columns:
    c_data[column] = c_data[column].astype ("string")
    
number_columns = ['GDP', 'Year','Forecast']
for column in number_columns:
    c_data[column] = c_data[column].astype ("int32")
    
c_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 184 entries, 0 to 221
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Country   184 non-null    string
 1   Forecast  184 non-null    int32
 2   Year      184 non-null    int32
 3   GDP       184 non-null    int32
dtypes: int32(3), string(1)
memory usage: 5.0 KB

C:\Users\HP\AppData\Local\Temp\ipykernel_1932\1614154928.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  c_data[column] = c_data[column].astype ("string")
C:\Users\HP\AppData\Local\Temp\ipykernel_1932\1614154928.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  c_data[column] = c_data[column].astype ("int32")
C:\Users\HP\AppData\Local\Temp\ipykernel_1932\1614154928.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  c_data[column] = c_data[column].astype ("int32")
C:\Users\HP\AppData\Local\Temp\ipykernel_1932\1614154928.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  c_data[column] = c_data[column].astype ("int32")

In [30]:
# Groupby allows you to group rows based on a column and perform a function
# Mean GDP by region
c_data[["Country","GDP"]].groupby("Country").mean()

                             GDP
Country
Albania                  27178.0
Algeria                 263620.0
Andorra                   4040.0
Angola                   80397.0
Antigua and Barbuda       2225.0
...                          ...
Vanuatu                   1161.0
Vietnam                 476388.0
World                111326370.0
Zambia                   26326.0
Zimbabwe                 44188.0

[184 rows x 1 columns]

In [31]:
# Groupby allows you to group rows based on a column and perform a function
# Mean GDP by region
c_data[["Country","GDP"]].groupby("Country").sum()

                           GDP
Country
Albania                  27178
Algeria                 263620
Andorra                   4040
Angola                   80397
Antigua and Barbuda       2225
...                        ...
Vanuatu                   1161
Vietnam                 476388
World                111326370
Zambia                   26326
Zimbabwe                 44188

[184 rows x 1 columns]

In [32]:
# Median GDP by region
c_data[["Country","GDP"]].groupby("Country").median()

                             GDP
Country
Albania                  27178.0
Algeria                 263620.0
Andorra                   4040.0
Angola                   80397.0
Antigua and Barbuda       2225.0
...                          ...
Vanuatu                   1161.0
Vietnam                 476388.0
World                111326370.0
Zambia                   26326.0
Zimbabwe                 44188.0

[184 rows x 1 columns]

In [34]:
c_data.describe()

           Forecast    Year           GDP
count  1.840000e+02   184.0  1.840000e+02
mean   1.228773e+06  2025.0  1.198383e+06
std    8.778598e+06     0.0  8.575131e+06
min    6.500000e+01  2025.0  6.200000e+01
25%    1.481975e+04  2025.0  1.424025e+04
50%    5.157650e+04  2025.0  4.978900e+04
75%    3.083188e+05  2025.0  3.020478e+05
max    1.137957e+08  2025.0  1.113264e+08

In [37]:
# Taking a final look at our c_data dataframe
c_data[:5]

         Country   Forecast  Year        GDP
0          World  113795678  2025  111326370
1  United States   30507217  2025   29184890
2          China   19231705  2025   18743803
3        Germany    4744804  2025    4659929
4          India    4187017  2025    3912686

In [36]:
# Exporting our c_data dataframe as MS Excel File
filename = "Country_GDP.xlsx"
try:
    c_data.to_excel(filename)
except:
    print("Error: Unable to convert dataframe to a csv file")
else:
    print(f"The {filename} file successfully created.")

The Country_GDP.xlsx file successfully created.

In [22]:
# You can also investigating the unique values for Country column using set data structure
#unique_un_region_v2 = set(c_data['UN region'])
#print(unique_un_region_v2)

KeyError: 'UN region'

In [ ]:
#Deleting rows in UN Region column containing the special character (—)
c_data = c_data[~c_data['UN region'].str.contains("—", regex=False)]
c_data

In [ ]:
unique_un_region_v2 = set(c_data['UN region'])
print(unique_un_region_v2)

In [ ]:
# Confirming the structure of our dataframe
c_data.info()

In [ ]:
# Confirming the number of columns
print(f"The number of columns are: {len(c_data.columns)}")
c_data.columns

In [ ]:
# Changing all the columns with the object data type to string
number_columns = ['Country', 'UN region']
for column in number_columns:
    c_data[column] = c_data[column].astype ("string")
    
number_columns = ['GDP', 'Year','Forecast']
for column in number_columns:
    c_data[column] = c_data[column].astype ("int32")
    
c_data.info()

In [ ]:
# Groupby allows you to group rows based on a column and perform a function
# Mean GDP by region
c_data[["UN region","GDP"]].groupby("UN region").mean()

In [ ]:
# Groupby allows you to group rows based on a column and perform a function
# Mean GDP by region
c_data[["UN region","GDP"]].groupby("UN region").sum()

In [ ]:
# Median GDP by region
c_data[["UN region","GDP"]].groupby("UN region").median()

In [ ]:
# Taking a final look at our c_data dataframe
c_data[:5]

In [ ]:
# Exporting our c_data dataframe as MS Excel File
filename = "Country_GDP.xlsx"
try:
    c_data.to_excel(filename)
except:
    print("Error: Unable to convert dataframe to a csv file")
else:
    print(f"The {filename} file successfully created.")

## Dealing with "HTTP Error 403: Forbidden" with Pandas

In [38]:
investment_data = pd.read_html("https://www.investing.com/earnings-calendar/")[1]
investment_data

HTTPError: HTTP Error 403: Forbidden

In [39]:
!pip install html5lib

Collecting html5lib
  Downloading html5lib-1.1-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: six>=1.9 in c:\chm python class\myenv_pydata\lib\site-packages (from html5lib) (1.17.0)
Requirement already satisfied: webencodings in c:\chm python class\myenv_pydata\lib\site-packages (from html5lib) (0.5.1)
Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
Installing collected packages: html5lib
Successfully installed html5lib-1.1

In [40]:
## Let's try to read a secure site
import requests
import pandas as pd
url_add = "https://www.investing.com/earnings-calendar/"
response = requests.get(url_add)

if response.status_code == 200:
    df = pd.read_html(response.content)[0]
    print(df.head())
else:
    print(f'Request failed: HTTP Error 403: Forbidden')

        Unnamed: 0_level_0                                  Company  \
        Unnamed: 0_level_1                                  Company
0  Monday, August 11, 2025                  Monday, August 11, 2025
1                      NaN                     Grupo Mexico (GMBXF)
2                      NaN  Singapore Telecommunications PK (SGAPY)
3                      NaN                       Barrick Mining (B)
4                      NaN                      Franco-Nevada (FNV)

                       EPS               / Forecast                  Revenue  \
                       EPS               / Forecast                  Revenue
0  Monday, August 11, 2025  Monday, August 11, 2025  Monday, August 11, 2025
1                       --                 / 0.1286                       --
2                       --                 / 0.3104                       --
3                       --                 / 0.4366                       --
4                       --                   / 1.13                       --

                / Forecast               Market Cap                     Time  \
              / Forecast.1               Market Cap                     Time
0  Monday, August 11, 2025  Monday, August 11, 2025  Monday, August 11, 2025
1                  / 4.33B                   51.77B                      NaN
2                     / --                   50.55B                      NaN
3                  / 3.73B                   40.27B                      NaN
4                / 375.91M                   33.06B                      NaN

        Unnamed: 8_level_0
        Unnamed: 8_level_1
0  Monday, August 11, 2025
1                      NaN
2                      NaN
3                      NaN
4                      NaN

In [41]:
df

,Unnamed: 0_level_0,Company,EPS,/ Forecast,Revenue,/ Forecast,Market Cap,Time,Unnamed: 8_level_0
,Unnamed: 0_level_1,Company,EPS,/ Forecast,Revenue,/ Forecast.1,Market Cap,Time,Unnamed: 8_level_1
0,"Monday, August 11, 2025","Monday, August 11, 2025","Monday, August 11, 2025","Monday, August 11, 2025","Monday, August 11, 2025","Monday, August 11, 2025","Monday, August 11, 2025","Monday, August 11, 2025","Monday, August 11, 2025"
1,NaN,Grupo Mexico (GMBXF),--,/ 0.1286,--,/ 4.33B,51.77B,NaN,NaN
2,NaN,Singapore Telecommunications PK (SGAPY),--,/ 0.3104,--,/ --,50.55B,NaN,NaN
3,NaN,Barrick Mining (B),--,/ 0.4366,--,/ 3.73B,40.27B,NaN,NaN
4,NaN,Franco-Nevada (FNV),--,/ 1.13,--,/ 375.91M,33.06B,NaN,NaN
...,...,...,...,...,...,...,...,...,...
319,NaN,Sunworks (SUNWQ),--,/ --,--,/ --,56,NaN,NaN
320,NaN,Great Panther Mining (GPLDF),--,/ --,--,/ --,47,NaN,NaN
321,NaN,iSun (ISUNQ),--,/ -0.03,--,/ 29.13M,47,NaN,NaN
322,NaN,DermTech (DMTKQ),--,/ -0.52,--,/ 4.28M,35,NaN,NaN
323,NaN,mCloud Technologies (MCLDF),--,/ --,--,/ --,33,NaN,NaN

In [45]:
print(df.columns)
print(df.columns.nlevels)  # number of levels

MultiIndex([('Unnamed: 0_level_0', 'Unnamed: 0_level_1'),
            (           'Company',            'Company'),
            (               'EPS',                'EPS'),
            (        '/ Forecast',         '/ Forecast'),
            (           'Revenue',            'Revenue'),
            (        '/ Forecast',       '/ Forecast.1'),
            (        'Market Cap',         'Market Cap'),
            (              'Time',               'Time'),
            ('Unnamed: 8_level_0', 'Unnamed: 8_level_1')],
           )
2

In [46]:
# Delete a level of a multilevel column name
c_data.columns = c_data.columns.droplevel()
c_data

ValueError: Cannot remove 1 levels from an index with 1 levels: at least one level must be left.

### Solving "HTTP Error 403: Forbidden" with request module

In [42]:
import pandas as pd
import requests

url = 'https://tradingeconomics.com/currencies'
header = {
  "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36",
  "X-Requested-With": "XMLHttpRequest"
}

content = requests.get(url, headers=header)
secured_data = pd.read_html(content.text)
secured_data[0]

C:\Users\HP\AppData\Local\Temp\ipykernel_1932\1340644819.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  secured_data = pd.read_html(content.text)

,Unnamed: 0,Major,Price,Day,%,Weekly,Monthly,YTD,YoY,Date
0,NaN,EURUSD,1.16716,0.0032,0.27%,0.76%,0.06%,12.68%,6.73%,Aug/11
1,NaN,GBPUSD,1.34752,0.0030,0.22%,1.33%,0.36%,7.64%,5.52%,Aug/11
2,NaN,AUDUSD,0.65264,0.0010,0.15%,0.81%,-0.26%,5.44%,-0.89%,Aug/11
3,NaN,NZDUSD,0.59551,0.0004,0.07%,0.66%,-0.26%,6.47%,-1.11%,Aug/11
4,NaN,USDJPY,147.49600,0.1640,-0.11%,0.48%,-0.19%,-6.26%,0.34%,Aug/11
5,NaN,USDCNY,7.18511,0.0033,-0.05%,0.06%,0.17%,-2.08%,0.10%,Aug/11
6,NaN,USDCHF,0.80626,0.0017,-0.21%,-0.10%,1.02%,-11.15%,-6.77%,Aug/11
7,NaN,USDCAD,1.37512,0.0002,-0.01%,-0.13%,0.33%,-4.36%,0.07%,Aug/11
8,NaN,USDMXN,18.57920,0.0107,0.06%,-1.61%,-0.89%,-10.89%,-2.52%,Aug/11
9,NaN,USDINR,87.53100,0.0527,-0.06%,-0.43%,1.82%,2.28%,4.33%,Aug/11
10,NaN,USDBRL,5.43390,0.0004,-0.01%,-1.16%,-2.76%,-12.14%,-1.08%,Aug/11
11,NaN,USDRUB,79.81000,0.1900,-0.24%,-0.02%,2.19%,-29.68%,-12.30%,Aug/11
12,NaN,USDKRW,1387.87000,0.8300,-0.06%,0.16%,0.39%,-6.11%,1.36%,Aug/11
13,NaN,DXY,98.06000,0.1200,-0.12%,-0.73%,-0.02%,-9.61%,-4.87%,Aug/11
14,NaN,USDTRY,40.75640,0.1086,0.27%,0.32%,1.46%,15.34%,21.61%,Aug/11
15,NaN,USDSEK,9.55020,0.0179,-0.19%,-0.96%,-0.69%,-13.68%,-9.23%,Aug/11
16,NaN,USDPLN,3.63745,0.0066,-0.18%,-1.40%,-0.26%,-11.94%,-7.60%,Aug/11
17,NaN,USDNOK,10.25619,0.0230,-0.22%,0.05%,1.18%,-9.91%,-5.09%,Aug/11
18,NaN,USDZAR,17.70850,0.0329,-0.19%,-1.25%,-1.04%,-6.06%,-2.98%,Aug/11
19,NaN,USDDKK,6.39543,0.0152,-0.24%,-0.72%,-0.04%,-11.16%,-6.28%,Aug/11
20,NaN,USDSGD,1.28356,0.0005,-0.04%,-0.25%,0.08%,-6.01%,-3.05%,Aug/11
21,NaN,USDILS,3.42310,0.0038,-0.11%,0.21%,2.31%,-5.89%,-8.96%,Aug/11
22,NaN,USDHKD,7.84987,0.0004,0.00%,0.01%,0.00%,1.07%,0.74%,Aug/11
23,NaN,USDCLP,968.85000,0.2000,-0.02%,-0.05%,1.99%,-2.57%,3.92%,Aug/08
24,NaN,USDPKR,283.47800,0.3220,-0.11%,-0.04%,-0.34%,1.83%,1.68%,Aug/11
25,NaN,USDCZK,20.92900,0.0392,-0.19%,-1.37%,-1.00%,-13.97%,-9.05%,Aug/11
26,NaN,USDHUF,338.64800,0.5300,-0.16%,-1.65%,-1.16%,-14.74%,-5.96%,Aug/11

### Pandas authorization by user and password

In [ ]:
import requests
import pandas as pd

url = 'https://en-gb.facebook.com/login.php'
username = 'dr_sam@yahoo.com'
password = 'XXueyjdhhernf'

response = requests.get(url, auth=(username, password))

if response.status_code == 200:
    df = pd.read_html(response.content)[0]
    print(df.head())
else:
    print(f'Request failed')